### ISSUE TITLE
Unhandled Error Checking Pings

### ISSUE THREAD

**Issue by Banjoau** [lukealford/aussiebb_tray#16]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
Getting this unhandled error report when aunt is checking latency.  Happens after aunt checks Adelaide, so while checking Perth.  Maybe Perth IP is unavailable? This is from Mac OS version but I get a similar error on Windows.

```Unhandled Error
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Tcpie.<anonymous> (/Applications/aussiebb_aunt.app/Contents/Resources/app.asar/src/main.js:372:24)
    at checkEnd (/Applications/aussiebb_aunt.app/Contents/Resources/app.asar/node_modules/tcpie/index.js:118:10)
    at Socket._socket.on (/Applications/aussiebb_aunt.app/Contents/Resources/app.asar/node_modules/tcpie/index.js:53:7)```
```

 After I acknowledge the error report there's just the green arc chasing its tail.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Happens whenever I click on the network (third) icon.

* **Please tell us about your environment:**
  
  - Version: 1.0.3
  - Operating system: Mac OS 10.14.5  

Also a similar error with Win 8.1

**Comment by ghost** [comment]
This is because we are not handling a failed response correctly, I'll get this fixed up for the next release.

**Comment by ghost** [comment]
This has now been fixed for the next version.
