### ISSUE TITLE
Wrong % used

### ISSUE THREAD

**Issue by DavidFW1960** [lukealford/aussiebb_tray#2]
Your meter shows 5% used of my unlimited with double data plan. 5% of 200000 is 10000gb and I have actually used 571gb or 0.29%

**Comment by tegregg** [comment]
Similar to above.  I have 834GB of 1TB left and it is calculating it as 79.58% rather than 83.4%

**Comment by lukealford** [comment]
Interesting, I'll look into this! 

if you can both log into 
https://my.aussiebroadband.com.au/usage.php?xml=yes

if you can  paste the xml result you get into this issue, I'll have a better chance at debugging this or alternatively run the dev command and you will see a output in the console.

**Comment by DavidFW1960** [comment]
It's calculating it wrong. 
My Rainmeter one and the other one at the start of the thread both calculate it correctly.
I'm sticking with my rainmeter usage meter anyway - just thought you'd like to know.

<usage>
<down1>524278339294</down1>
<up1>50653804153</up1>
<allowance1_mb>200000000</allowance1_mb>
<left1>199425067856553</left1>
<down2>0</down2>
<up2>0</up2>
<allowance2_mb>0</allowance2_mb>
<left2>0</left2>
<lastupdated>2018-04-29 14:41:36</lastupdated>
<rollover>6</rollover>
</usage>

**Comment by DavidFW1960** [comment]
usage>
<down1>524278339294</down1>
<up1>50653804153</up1>
<allowance1_mb>200000000</allowance1_mb>
<left1>199425067856553</left1>
<down2>0</down2>
<up2>0</up2>
<allowance2_mb>0</allowance2_mb>
<left2>0</left2>
<lastupdated>2018-04-29 14:41:36</lastupdated>
<rollover>6</rollover>
</usage>

**Comment by lukealford** [comment]
yeah it was my conversion of `<left1></left>,` I've fixed it in the latest commit. 

Will be all fixed in 0.0.4-alpha which has linux support.

I've honestly never used rainmeter, This will be updated to be more feature full in the future hopefully I can win you over in the future 👍
