### ISSUE TITLE
Replace login window with full result

### ISSUE THREAD

**Issue by tegregg** [lukealford/aussiebb_tray#3]
Would like the detail shown in the panel when you click on the tray icon rather than it just showing logon details.  Logon details could be done via right click menu which then gives you real estate to show usage graphs etc in the panel.  Hovering to get detail in cool, but the option to click and get detail would also be great.

Thanks for pulling this together - going well so far.

**Comment by lukealford** [comment]
Hey Tegregg, 

This is definitively planned.  I'm going to have the login panel update, just working out some issues with updating that panel :) but 👍 for the suggestion

**Comment by lukealford** [comment]
Here is a preview of what I'm working with. 
![aussebb_usage-tray-fulldata-wip](https://user-images.githubusercontent.com/679094/39404066-6ed07c18-4bce-11e8-9319-6664ca734325.png)

This is all the data we get from the XML, for me to do anything more I'll need to scrape the actual real website that has the drop down per month.

**Comment by tegregg** [comment]
Looks good.  I think it the MUM one also did a calculation to see if you were ahead or behind.  You could do a calc of total per day based on the full download limit and full number of days and then compare that against usage to determine if someone is ahead or behind where the need to be and by how much.

**Comment by lukealford** [comment]
Ahh I knew I was forgetting something! I'll add that calculation and release a new version but before I do this I want to have auto login work so you don't have to re-login every time you open the app to see this updated window.

**Comment by lukealford** [comment]
This was completed in [Release 0.5.5-beta](https://github.com/lukealford/aussiebb_tray/releases/tag/v0.5.5-beta)
